# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Akedo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Akedo
  pod 'SwiftyJSON'
  pod 'Alamofire', '3.1.0'

  target 'AkedoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AkedoUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end